name: Build Package
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      image_tag:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: ghcr.io/${{ github.repository }}/vitasdk:${{ inputs.image_tag }}
    if: inputs.package != '__dummy__'

    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          path: package
          merge-multiple: true

      - name: Install dependencies into sysroot

        run: |
          export VITASDK=/usr/local/vitasdk
          mkdir -p $VITASDK/arm-vita-eabi
          if [ -d "package" ]; then
            for file in package/*.tar.xz; do
              if [ -f "$file" ]; then
                pkgname=$(basename "$file" .tar.xz)
                # Avoid conflict between openssl versions if both are present
                if [ "$pkgname" == "openssl" ] && [ -f "package/openssl-1.1.1.tar.xz" ]; then
                  continue
                fi
                tar -C $VITASDK/arm-vita-eabi/ -xvf "$file"
              fi
            done
          fi

      - name: Build package
        run: |
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          bash ./build.sh ${{ inputs.package }}
      - name: Rename package
        run: |
          export FILE=`echo ${{ inputs.package }}/*-arm.tar.xz`
          mv $FILE ${{ inputs.package }}/${{ inputs.package }}.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package }}
          path: ${{ inputs.package }}/${{ inputs.package }}.tar.xz
          if-no-files-found: error
