name: Packages

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"
  repository_dispatch:
    types: [run_build]

jobs:
  prepare_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        id: set-matrix
        run: |
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          node create-matrix.js >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          TAG=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      tag: ${{ steps.set-matrix.outputs.tag }}

  prepare_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/vitasdk:${{ needs.prepare_jobs.outputs.tag }}

  build_tier0_main:
    needs: [prepare_jobs, prepare_docker]

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier0_main }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier0_slow:
    needs: [prepare_jobs, prepare_docker]

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier0_slow }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier1_main:
    needs: [prepare_jobs, prepare_docker, build_tier0_main]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier1_main }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier1_slow:
    needs: [prepare_jobs, prepare_docker, build_tier0_main, build_tier0_slow]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier1_slow }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier2_main:
    needs: [prepare_jobs, prepare_docker, build_tier1_main]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier2_main }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier2_slow:
    needs: [prepare_jobs, prepare_docker, build_tier1_main, build_tier1_slow]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier2_slow }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier3_main:
    needs: [prepare_jobs, prepare_docker, build_tier2_main]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier3_main }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier3_slow:
    needs: [prepare_jobs, prepare_docker, build_tier2_main, build_tier2_slow]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier3_slow }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
      image_tag: ${{ needs.prepare_jobs.outputs.tag }}
    secrets: inherit

  build_tier4_main:
    needs: [prepare_jobs, prepare_docker, build_tier3_main]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier4_main }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  build_tier4_slow:
    needs: [prepare_jobs, prepare_docker, build_tier3_main, build_tier3_slow]


    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.prepare_jobs.outputs.matrix).tier4_slow }}
    uses: ./.github/workflows/build_package.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  upload-releases:
    needs: [prepare_jobs, build_tier0_main, build_tier0_slow, build_tier1_main, build_tier1_slow, build_tier2_main, build_tier2_slow, build_tier3_main, build_tier3_slow, build_tier4_main, build_tier4_slow]
    runs-on: ubuntu-latest
    if: contains(github.ref,'refs/heads/master')
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          path: package
          merge-multiple: true
      - name: Upload release assets
        run: gh release upload master package/*.tar.xz --clobber
        env:
          GITHUB_TOKEN: ${{ github.token }}
